name: CI
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: yarn install
      - run: yarn build
      # - run: yarn test
      - run: yarn lint
      - run: yarn check-types
